/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyDockerRuntimeModule;
import org.xtext.example.mydsl.MyDockerStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDockerIdeSetup extends MyDockerStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDockerRuntimeModule(), new MyDockerIdeModule()));
	}
	
}
