/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalMyDockerParser;
import org.xtext.example.mydsl.services.MyDockerGrammarAccess;

public class MyDockerParser extends AbstractAntlrParser {

	@Inject
	private MyDockerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyDockerParser createParser(XtextTokenStream stream) {
		return new InternalMyDockerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MyDockerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDockerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
