/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDockerStandaloneSetup extends MyDockerStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDockerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
